### ISSUE TITLE
missing certs in latest release.

### ISSUE THREAD

**Issue by GeJ** [noxxi/p5-io-socket-ssl#66] opened 2018-01-21 21:59 UTC
I tried to update I:S:S this morning but the sni*.t tests failed, complaining about 1 test ran out of 17 planned. Running said tests verbosely, I get this error : 

`not ok # SSL_cert_file certs/server2-cert.pem can't be used: No such file or directory at /usr/home/xxx/.cpanm/work/1516570603.23798/IO-Socket-SSL-2.053/lib/IO/Socket/SSL.pm line 2256`

And indeed, the file is missing in the certs directory. Also, there is no mention of this file in MANIFEST. They seem to be fairly new (github claims they were created 7 days ago), could it be that you forgot to add them in your release procedure?

Best regards,

**Comment by noxxi** [comment] 2018-01-22 05:12
Thanks for the bug report. The issue is fixed in the just released version 2.054 by including the missing test certificates

**Closed by noxxi** 2018-01-22 05:12 UTC
